server:
  port: 8763

spring:
  application:
    name: config-server
  cloud:                # Cloud config
    config:
      server:
        git:
          uri: https://github.com/tarun-vishnoi/spring-cloud-config-properties.git
          clone-on-start: true
          timeout: 10
    bus:
      enabled: true
  kafka:                # Kafka config
    bootstrap-servers:
    - http://localhost:9092
  zipkin:               # Sleuth-Zipkin config
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
      
# Eureka

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# Actuators
      
management:
  endpoints:
    web:
      exposure:
        include:
        - bus-refresh
        - beans
        - health
        - routes
        - httptrace
        - mappings
